# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: day2.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='day2.proto',
  package='day2',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\nday2.proto\x12\x04\x64\x61y2\"k\n\x05Stats\x12\x0e\n\x06level1\x18\x01 \x01(\x03\x12\x10\n\x08\x65xp_curr\x18\x02 \x01(\x03\x12\x0f\n\x07\x65xp_max\x18\x03 \x01(\x03\x12\x0e\n\x06level2\x18\x04 \x01(\x03\x12\x0f\n\x07hp_curr\x18\x05 \x01(\x03\x12\x0e\n\x06hp_max\x18\x06 \x01(\x03\"l\n\nObjectCost\x12\x0c\n\x04obj1\x18\x01 \x01(\x03\x12$\n\x02\x62s\x18\x02 \x01(\x0e\x32\x18.day2.ObjectCost.BuySell\x12\x0c\n\x04\x63ost\x18\x03 \x01(\x03\"\x1c\n\x07\x42uySell\x12\x08\n\x04SELL\x10\x00\x12\x07\n\x03\x42UY\x10\x01\"V\n\x06Object\x12\x0c\n\x04obj1\x18\x01 \x01(\x03\x12\x10\n\x08strength\x18\x02 \x01(\x03\x12\x0c\n\x04obj3\x18\x03 \x01(\x0c\x12\x1e\n\x04\x63ost\x18\x04 \x03(\x0b\x32\x10.day2.ObjectCost\"_\n\tInventory\x12!\n\x04type\x18\x01 \x01(\x0e\x32\x13.day2.InventoryType\x12\x1d\n\x07objects\x18\x02 \x03(\x0b\x32\x0c.day2.Object\x12\x10\n\x08\x63\x61pacity\x18\x03 \x01(\x03\"W\n\x06Person\x12\r\n\x05level\x18\x01 \x01(\x03\x12\x1a\n\x05stats\x18\x02 \x01(\x0b\x32\x0b.day2.Stats\x12\"\n\tinventory\x18\x03 \x03(\x0b\x32\x0f.day2.Inventory\"\x80\x01\n\x08SendData\x12\x0f\n\x05type1\x18\x01 \x01(\x0cH\x00\x12\x1e\n\x06person\x18\x02 \x01(\x0b\x32\x0c.day2.PersonH\x00\x12\x0f\n\x05type3\x18\x03 \x01(\x0cH\x00\x12\x0f\n\x05type4\x18\x04 \x01(\x0cH\x00\x12\x0f\n\x05type5\x18\x05 \x01(\x0cH\x00\x42\x10\n\x0eSendData_oneof*2\n\rInventoryType\x12\x07\n\x03\x42\x41G\x10\x00\x12\t\n\x05STASH\x10\x01\x12\r\n\tEQUIPMENT\x10\x02\x62\x06proto3'
)

_INVENTORYTYPE = _descriptor.EnumDescriptor(
  name='InventoryType',
  full_name='day2.InventoryType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BAG', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STASH', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EQUIPMENT', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=644,
  serialized_end=694,
)
_sym_db.RegisterEnumDescriptor(_INVENTORYTYPE)

InventoryType = enum_type_wrapper.EnumTypeWrapper(_INVENTORYTYPE)
BAG = 0
STASH = 1
EQUIPMENT = 2


_OBJECTCOST_BUYSELL = _descriptor.EnumDescriptor(
  name='BuySell',
  full_name='day2.ObjectCost.BuySell',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SELL', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BUY', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=209,
  serialized_end=237,
)
_sym_db.RegisterEnumDescriptor(_OBJECTCOST_BUYSELL)


_STATS = _descriptor.Descriptor(
  name='Stats',
  full_name='day2.Stats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='level1', full_name='day2.Stats.level1', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exp_curr', full_name='day2.Stats.exp_curr', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exp_max', full_name='day2.Stats.exp_max', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='level2', full_name='day2.Stats.level2', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hp_curr', full_name='day2.Stats.hp_curr', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hp_max', full_name='day2.Stats.hp_max', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=127,
)


_OBJECTCOST = _descriptor.Descriptor(
  name='ObjectCost',
  full_name='day2.ObjectCost',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='obj1', full_name='day2.ObjectCost.obj1', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bs', full_name='day2.ObjectCost.bs', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cost', full_name='day2.ObjectCost.cost', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _OBJECTCOST_BUYSELL,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=237,
)


_OBJECT = _descriptor.Descriptor(
  name='Object',
  full_name='day2.Object',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='obj1', full_name='day2.Object.obj1', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='strength', full_name='day2.Object.strength', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='obj3', full_name='day2.Object.obj3', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cost', full_name='day2.Object.cost', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=239,
  serialized_end=325,
)


_INVENTORY = _descriptor.Descriptor(
  name='Inventory',
  full_name='day2.Inventory',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='day2.Inventory.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='objects', full_name='day2.Inventory.objects', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='capacity', full_name='day2.Inventory.capacity', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=327,
  serialized_end=422,
)


_PERSON = _descriptor.Descriptor(
  name='Person',
  full_name='day2.Person',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='level', full_name='day2.Person.level', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stats', full_name='day2.Person.stats', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inventory', full_name='day2.Person.inventory', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=424,
  serialized_end=511,
)


_SENDDATA = _descriptor.Descriptor(
  name='SendData',
  full_name='day2.SendData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type1', full_name='day2.SendData.type1', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='person', full_name='day2.SendData.person', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type3', full_name='day2.SendData.type3', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type4', full_name='day2.SendData.type4', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type5', full_name='day2.SendData.type5', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='SendData_oneof', full_name='day2.SendData.SendData_oneof',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=514,
  serialized_end=642,
)

_OBJECTCOST.fields_by_name['bs'].enum_type = _OBJECTCOST_BUYSELL
_OBJECTCOST_BUYSELL.containing_type = _OBJECTCOST
_OBJECT.fields_by_name['cost'].message_type = _OBJECTCOST
_INVENTORY.fields_by_name['type'].enum_type = _INVENTORYTYPE
_INVENTORY.fields_by_name['objects'].message_type = _OBJECT
_PERSON.fields_by_name['stats'].message_type = _STATS
_PERSON.fields_by_name['inventory'].message_type = _INVENTORY
_SENDDATA.fields_by_name['person'].message_type = _PERSON
_SENDDATA.oneofs_by_name['SendData_oneof'].fields.append(
  _SENDDATA.fields_by_name['type1'])
_SENDDATA.fields_by_name['type1'].containing_oneof = _SENDDATA.oneofs_by_name['SendData_oneof']
_SENDDATA.oneofs_by_name['SendData_oneof'].fields.append(
  _SENDDATA.fields_by_name['person'])
_SENDDATA.fields_by_name['person'].containing_oneof = _SENDDATA.oneofs_by_name['SendData_oneof']
_SENDDATA.oneofs_by_name['SendData_oneof'].fields.append(
  _SENDDATA.fields_by_name['type3'])
_SENDDATA.fields_by_name['type3'].containing_oneof = _SENDDATA.oneofs_by_name['SendData_oneof']
_SENDDATA.oneofs_by_name['SendData_oneof'].fields.append(
  _SENDDATA.fields_by_name['type4'])
_SENDDATA.fields_by_name['type4'].containing_oneof = _SENDDATA.oneofs_by_name['SendData_oneof']
_SENDDATA.oneofs_by_name['SendData_oneof'].fields.append(
  _SENDDATA.fields_by_name['type5'])
_SENDDATA.fields_by_name['type5'].containing_oneof = _SENDDATA.oneofs_by_name['SendData_oneof']
DESCRIPTOR.message_types_by_name['Stats'] = _STATS
DESCRIPTOR.message_types_by_name['ObjectCost'] = _OBJECTCOST
DESCRIPTOR.message_types_by_name['Object'] = _OBJECT
DESCRIPTOR.message_types_by_name['Inventory'] = _INVENTORY
DESCRIPTOR.message_types_by_name['Person'] = _PERSON
DESCRIPTOR.message_types_by_name['SendData'] = _SENDDATA
DESCRIPTOR.enum_types_by_name['InventoryType'] = _INVENTORYTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Stats = _reflection.GeneratedProtocolMessageType('Stats', (_message.Message,), {
  'DESCRIPTOR' : _STATS,
  '__module__' : 'day2_pb2'
  # @@protoc_insertion_point(class_scope:day2.Stats)
  })
_sym_db.RegisterMessage(Stats)

ObjectCost = _reflection.GeneratedProtocolMessageType('ObjectCost', (_message.Message,), {
  'DESCRIPTOR' : _OBJECTCOST,
  '__module__' : 'day2_pb2'
  # @@protoc_insertion_point(class_scope:day2.ObjectCost)
  })
_sym_db.RegisterMessage(ObjectCost)

Object = _reflection.GeneratedProtocolMessageType('Object', (_message.Message,), {
  'DESCRIPTOR' : _OBJECT,
  '__module__' : 'day2_pb2'
  # @@protoc_insertion_point(class_scope:day2.Object)
  })
_sym_db.RegisterMessage(Object)

Inventory = _reflection.GeneratedProtocolMessageType('Inventory', (_message.Message,), {
  'DESCRIPTOR' : _INVENTORY,
  '__module__' : 'day2_pb2'
  # @@protoc_insertion_point(class_scope:day2.Inventory)
  })
_sym_db.RegisterMessage(Inventory)

Person = _reflection.GeneratedProtocolMessageType('Person', (_message.Message,), {
  'DESCRIPTOR' : _PERSON,
  '__module__' : 'day2_pb2'
  # @@protoc_insertion_point(class_scope:day2.Person)
  })
_sym_db.RegisterMessage(Person)

SendData = _reflection.GeneratedProtocolMessageType('SendData', (_message.Message,), {
  'DESCRIPTOR' : _SENDDATA,
  '__module__' : 'day2_pb2'
  # @@protoc_insertion_point(class_scope:day2.SendData)
  })
_sym_db.RegisterMessage(SendData)


# @@protoc_insertion_point(module_scope)
